import { defineConfig, devices } from "@playwright/test";

/**
 * E2E tests run against the local dev server + local Supabase stack.
 *
 * Local: ensure Supabase is running (`pnpm run supabase:start`) and admin is
 * seeded (`pnpm run seed:admin`), or use `pnpm run test:e2e:local`.
 *
 * Playwright starts the Vite dev server via webServer (after auth setup projects).
 * Auth storage states are generated by setup projects and are gitignored.
 */
export default defineConfig({
  testDir: "./e2e",
  testMatch: "**/*.spec.ts",
  outputDir: "./e2e/results",
  fullyParallel: false,
  timeout: process.env.CI ? 60_000 : 30_000,
  retries: process.env.CI ? 2 : 0,
  reporter: "list",
  webServer: {
    command: process.env.CI ? "CF_WORKERS=0 pnpm exec vite dev" : "bash scripts/e2e-web-server.sh",
    url: "http://localhost:5173",
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
  use: {
    baseURL: "http://localhost:5173",
    locale: "es",
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "setup-admin",
      testMatch: /auth\.admin\.setup\.ts/,
    },
    {
      name: "setup-tech",
      testMatch: /auth\.tech\.setup\.ts/,
    },
    {
      name: "admin",
      testMatch: /order-flow\.spec\.ts/,
      dependencies: ["setup-admin"],
      use: {
        ...devices["Desktop Chrome"],
        storageState: "e2e/fixtures/admin-state.json",
      },
    },
    {
      name: "technician",
      testMatch: /technician-access\.spec\.ts/,
      dependencies: ["setup-tech"],
      use: {
        ...devices["Desktop Chrome"],
        storageState: "e2e/fixtures/technician-state.json",
      },
    },
    {
      name: "no-auth",
      testMatch: /auth\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],
});
